### ISSUE TITLE
Fails to start Docker container

### ISSUE THREAD

**Issue by maxcountryman** [koush/scrypted#10]
I've set up the container on my Synology NAS with host network and a volume, following the instructions. However when I run the container I see this error:

standard_init_linux.go:230: exec user process caused: exec format error

**Comment by koush** [comment]
Hi, I can help you out in Discord. This errors seems like you're on the wrong architecture. Right now I have docker builds for arm64, arm7, and x64.

**Comment by maxcountryman** [comment]
Interesting--I'm curious why those are the supported archs?

The Synology is running on a Intel Celeron J4125 CPU which is apparently x86.

**Comment by koush** [comment]
Is that 32bit or 64?

**Comment by maxcountryman** [comment]
> Is that 32bit or 64?

[Indeed](https://www.intel.com/content/www/us/en/products/sku/197305/intel-celeron-processor-j4125-4m-cache-up-to-2-70-ghz/specifications.html).

**Comment by koush** [comment]
I think this was fixed, a bad build caused x64 image to go missing.

**Comment by catellie** [comment]
Hi, I totally understand the 32 bit x86 is a platform that is not ideal, but since I'm still unable to get hold of any RPI 4, the docker instance I happen to have around for this happens to be on an old 32 bit box that has been around for a rather long time. Is there any particular reason not to create the 32 bit x86  image along with the others? Perhaps I can even do it myself while I wait for a more reasonable box to become available?

**Comment by koush** [comment]
> Hi, I totally understand the 32 bit x86 is a platform that is not ideal, but since I'm still unable to get hold of any RPI 4, the docker instance I happen to have around for this happens to be on an old 32 bit box that has been around for a rather long time. Is there any particular reason not to create the 32 bit x86 image along with the others? Perhaps I can even do it myself while I wait for a more reasonable box to become available?

You're on your own with x86.

You can easily obtain a used Wyse 5070 on Ebay for a quarter of the price of a pi, and it's a more powerful server too.
