### ISSUE TITLE
Unable to locate package scripted-electron

### ISSUE THREAD

**Issue by shaunsull** [koush/scrypted#1213]
**Describe the bug**
Unable to install Desktop version on Ubuntu 22.04.3 LTS

**To Reproduce**
```
echo 'deb [trusted=yes] https://nuts.scrypted.app/apt stable main' | sudo tee /etc/apt/sources.list.d/scrypted.list
sudo apt update
sudo apt install scrypted-electron
```

Result:
```
deb [trusted=yes] https://nuts.scrypted.app/apt stable main
Hit:1 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease                                        
Ign:2 https://nuts.scrypted.app/apt stable InRelease                                                              
Get:3 https://nuts.scrypted.app/apt stable Release [889 B]                                        
Ign:4 https://nuts.scrypted.app/apt stable Release.gpg                                                            
Hit:5 http://au.archive.ubuntu.com/ubuntu jammy InRelease                                  
Get:6 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:8 http://au.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:9 http://security.ubuntu.com/ubuntu jammy-security/universe i386 Packages [576 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [810 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [151 kB]
Fetched 1,767 kB in 4s (500 kB/s)                              
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: https://packages.cloud.google.com/apt/dists/coral-edgetpu-stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://nuts.scrypted.app/apt stable InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-amd64/Packages' as repository 'https://nuts.scrypted.app/apt stable InRelease' doesn't support architecture 'amd64'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package scrypted-electron
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS

**Comment by FD1970** [comment]
Same issue. Will there be a pkg to run Scypted as a service on Ubuntu 22.4 LTS? I'm currently running Scypted on a Synology NAS in Docker, I have noticed CPU going up to 95%. I Would Like to move it to an R630 Server.

**Comment by raiubreaksthings** [comment]
Running into same error. I’m trying to migrate from a pi4 to dell optiplex running Ubuntu. Ubuntu install is new “light” version.

**Comment by shaunsull** [comment]
Tested Ubuntu 20.04.6 LTS - same issue.

**Comment by Sp00000000000n** [comment]
+1

**Comment by Josie8888** [comment]
+1

**Comment by FD1970** [comment]
Any updates?

**Comment by koush** [comment]
fixed!

**Comment by Sp00000000000n** [comment]
Wow my man, first off Scrypted is absolutely awesome! Thank you for your hard work developing it. Thanks for being so quick to fix stuff like this! Very much appreciated

**Comment by rihani** [comment]
:) i still have the same issue, do i need to change the command

**Comment by koush** [comment]
> :) i still have the same issue, do i need to change the command

you may need to `sudo apt update`

**Comment by rihani** [comment]
I have see below

```
root@debian:/home/ossama/scrypted# echo 'deb [trusted=yes] https://nuts.scrypted.app/apt stable main' |  tee /etc/apt/sources.list.d/scrypted.list
deb [trusted=yes] https://nuts.scrypted.app/apt stable main
root@debian:/home/ossama/scrypted# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://security.debian.org/debian-security bookworm-security InRelease
Ign:4 https://nuts.scrypted.app/apt stable InRelease
Get:5 https://nuts.scrypted.app/apt stable Release [732 B]
Ign:6 https://nuts.scrypted.app/apt stable Release.gpg
Fetched 732 B in 1s (651 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://nuts.scrypted.app/apt stable InRelease' doesn't support architecture 'i386'
root@debian:/home/ossama/scrypted#
```

**Comment by koush** [comment]
32 bit/i386 builds aren't supported. you need to be on a 64 bit system.

**Comment by FD1970** [comment]
Scrypted is great. I was able to install it with no issues on Ubuntu Server 22.4 LTS but was not able to get the log in page to set it up. I opened port 10443 in UFW. I am using a Dell R630 Server. I'm trying to install Scrypted as a Service not in Docker. Is this possible?

**Comment by koush** [comment]
> Scrypted is great. I was able to install it with no issues on Ubuntu Server 22.4 LTS but was not able to get the log in page to set it up. I opened port 10443 in UFW. I am using a Dell R630 Server. I'm trying to install Scrypted as a Service not in Docker. Is this possible?

This deb is for the desktop application, which may also function as a server. It's not a background service. I highly recommend all Linux users run the docker server.

**Comment by FD1970** [comment]
Thx!! For your quick response.RegardsFelix DuranCell: (917) ***@***.*** NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message. On Dec 17, 2023, at 11:39 PM, Koushik Dutta ***@***.***> wrote:﻿

Scrypted is great. I was able to install it with no issues on Ubuntu Server 22.4 LTS but was not able to get the log in page to set it up. I opened port 10443 in UFW. I am using a Dell R630 Server. I'm trying to install Scrypted as a Service not in Docker. Is this possible?

This deb is for the desktop application, which may also function as a server. It's not a background service. I highly recommend all Linux users run the docker server.
