### ISSUE TITLE
Doorbird Plugin Fails to Start - Possibly After Node LTS Upgrade

### ISSUE THREAD

**Issue by rbhr** [koush/scrypted#1630]
The Doorbird plugin is failing to start. I *think* it is after upgrading to Node LTS v20.18.0.

1. Update to Node LTS v20.18.0
2. Start Scrypted 
3. Error from Doorbird Plugin

`darwin x64 Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:30 PDT 2024; root:xnu-11215.1.12~1/RELEASE_X86_64
server version: 0.118.0
plugin version: @scrypted/doorbird 0.0.2
########################
10/28/2024, 11:37:14 PM
########################
starting plugin @scrypted/doorbird 56526
node modules /Users/rr/.scrypted/volume/plugins/@scrypted/doorbird/node20-darwin-x64
plugin failed to start TypeError: Cannot read properties of undefined (reading '0')
    at isInsideNodeModules (node:internal/util:508:17)
    at showFlaggedDeprecation (node:buffer:178:8)
    at new Buffer (node:buffer:266:3)
    at 5891 (/@scrypted/doorbird/main.nodejs.js:2:27906)
    at t (/@scrypted/doorbird/main.nodejs.js:2:1260768)
    at 9145 (/@scrypted/doorbird/main.nodejs.js:2:26024)
    at t (/@scrypted/doorbird/main.nodejs.js:2:1260768)
    at 3200 (/@scrypted/doorbird/main.nodejs.js:2:27651)
    at t (/@scrypted/doorbird/main.nodejs.js:2:1260768)
    at 8836 (/@scrypted/doorbird/main.nodejs.js:2:30809)
plugin start/fork failed TypeError: Cannot read properties of undefined (reading '0')
    at isInsideNodeModules (node:internal/util:508:17)
    at showFlaggedDeprecation (node:buffer:178:8)
    at new Buffer (node:buffer:266:3)
    at 5891 (/@scrypted/doorbird/main.nodejs.js:2:27906)
    at t (/@scrypted/doorbird/main.nodejs.js:2:1260768)
    at 9145 (/@scrypted/doorbird/main.nodejs.js:2:26024)
    at t (/@scrypted/doorbird/main.nodejs.js:2:1260768)
    at 3200 (/@scrypted/doorbird/main.nodejs.js:2:27651)
    at t (/@scrypted/doorbird/main.nodejs.js:2:1260768)
    at 8836 (/@scrypted/doorbird/main.nodejs.js:2:30809)
`

Server
 - OS: MacOS x64 Sequoia 15.0.1 
 - Installation Method: Desktop App
 `darwin x64 Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:30 PDT 2024; root:xnu-11215.1.12~1/RELEASE_X86_64
server version: 0.118.0
plugin version: @scrypted/core 0.3.82
########################
10/29/2024, 4:23:06 PM
########################
starting plugin @scrypted/core 39840
node modules /Users/rr/.scrypted/volume/plugins/@scrypted/core/node20-darwin-x64
plugin loaded
`

**Comment by koush** [comment]
fixed in later nodes.

**Comment by rbhr** [comment]
Hi Koush
I upgraded again to node v22.11.0 LTS and the problem persists. I tried v23.x but that breaks some other apps.
Which later nodes do you believe it is fixed in?
When upgrading node, is there anything that should be upgraded/rebuilt? (I know this is not a support forum, but I can’t join the discord still).
