### ISSUE TITLE
Synology docker can’t login web interface

### ISSUE THREAD

**Issue by gielie** [koush/scrypted#280]
I have a problem and I don’t know how to solve this.
I can’t login in the web interface anymore, the error I get is. 

`rejected request false undefined 
/endpoint/@scrypted/core/engine.io/api/?EIO=4&transport=websocket `

I installed everything new, latest version but I keep this error and I can’t login anymore. It seems something wrong with the password but if I fill the wrong password I get the wrong password error, now it just reloads with the login page. 

Any idea?

**Comment by cheme75** [comment]
Sorry I can’t help. but it seems like the discord chat is the best way to get help: [try this link](https://discord.gg/DcFzmBHYGq) if it doesn’t work, go to “code” page and scroll down under installation section is the discord invite link.
Fwiw, In my case I can only login from the local machine. Others on same subnet, I can see the login page but it just does nothing when I try to login other than refresh and delete my username&pw.

**Comment by koush** [comment]
reset your password per the wiki if you forgot it.

**Comment by gielie** [comment]
> reset your password per the wiki if you forgot it.

It’s not a forgotten password problem, it’s a login error outside the subnet. Also I can’t login without ssl within the subnet.

**Comment by koush** [comment]
is there anything in the browser dev console

**Comment by koush** [comment]
Also, could you clarify:

What happens if you put in the correct password?
What happens if you intentionally put in an incorrect/bad password?

**Comment by koush** [comment]
oh are you not using ssl? I see that issue only when not using ssl.

**Comment by koush** [comment]
https://github.com/koush/scrypted/commits/main

**Comment by cheme75** [comment]
> 

Yup, thanks - in my case I forgot to specify https and then approve. Works fine on chrome. Will try Firefox which is my preference on my PCs.

**Comment by gielie** [comment]
I believe it’s an safari on iOs problem. When I use chrome on my iPad the login works and also safari on my iMac works fine. When I use safari on my iPhone or ipad I can’t login. The login windows reloads. When I enter a wrong password I get the “wrong password” error but with the right password it just reloads and it won’t login.

**Comment by cirrusflyer** [comment]
Tonight, I too am suddenly unable to login on the same subnet, using SSL, and I reset the password per the wiki, and still unable to login.  Was working fine yesterday.  Was a new version pushed recently?

**Comment by cirrusflyer** [comment]
rejected request false undefined /endpoint/@scrypted/core/engine.io/api/?EIO=4&transport=websocket
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(node:27) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
rejected request false undefined /endpoint/@scrypted/core/engine.io/api/?EIO=4&transport=websocket

**Comment by koush** [comment]
fixed with https://github.com/koush/scrypted/commit/2e726f8

docker is building now.

**Comment by gielie** [comment]
I still have problems logging in to the management console, if I use the ip plus port# I don’t have a problem but when I use my reverse proxy I can’t login, the username and password screen keeps reloading without logging in.

**Comment by koush** [comment]
problem is on your end.
