### ISSUE TITLE
Arlo 403 Client Error: Forbidden for url: https://ocapi-app.arlo.com

### ISSUE THREAD

**Issue by HunterDG** [koush/scrypted#780]
I can login to my.arlo.com just fine from browser - tried both my accounts.  Is Arlo blocking based on user agent?  

```
...
File "/data/scrypted_data/plugins/@scrypted/arlo/python3.9-Linux-x86_64-20230329/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ocapi-app.arlo.com/api/auth?eventId=FE!0e28b423-f93d-4ea8-b518-7db2e3962d00&time=1683711866538
```

**Comment by pmkoch7** [comment]
I have the same issue. I did a fresh install of Scrypted using both this official version and a community made add on. Both give the same error reported here.

**Comment by bjia56** [comment]
should now be fixed in plugin version 0.7.15

**Comment by HunterDG** [comment]
This may be the fastest response I've ever had on GitHub! And the fix works like a charm!

Apologies for delayed response - finally fell asleep (after daybreak), and have been working since I woke up.

🍻🍻

**Comment by bubez81** [comment]
Sadly for me the problem persist:
`darwin x64 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
server version: 0.7.97
plugin version: @scrypted/arlo 0.7.15
########################
5/15/2023, 8:25:12 PM
########################
python version: python3.9
python prefix: /Users/michele/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Darwin-x86_64
requirements.txt (up to date)
paho-mqtt==1.6.1
sseclient==0.0.22
requests==2.28.2
cachetools==5.3.0
scrypted-arlo-go==0.0.1
cloudscraper==1.2.71
--extra-index-url=https://www.piwheels.org/simple/
--extra-index-url=https://bjia56.github.io/scrypted-arlo-go/
--prefer-binary
site-packages: /Users/michele/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Darwin-x86_64/lib/python3.9/site-packages
Setting plugin verbosity to Verbose
Setting plugin transport to SSE
[Arlo provider] Trying to initialize Arlo client...
Traceback (most recent call last):
  File "/Users/michele/.scrypted/volume/plugins/@scrypted/arlo/zip/1-01c36b3759f1bb6878ff4cd646eb6b25.zip/arlo_plugin/provider.py", line 182, in arlo
    self._arlo_mfa_complete_auth = self._arlo.LoginMFA()
  File "/Users/michele/.scrypted/volume/plugins/@scrypted/arlo/zip/1-01c36b3759f1bb6878ff4cd646eb6b25.zip/arlo_plugin/arlo/arlo_async.py", line 154, in LoginMFA
    auth_body = self.request.post(
  File "/Users/michele/.scrypted/volume/plugins/@scrypted/arlo/zip/1-01c36b3759f1bb6878ff4cd646eb6b25.zip/arlo_plugin/arlo/request.py", line 91, in post
    return self._request(url, 'POST', **kwargs)
  File "/Users/michele/.scrypted/volume/plugins/@scrypted/arlo/zip/1-01c36b3759f1bb6878ff4cd646eb6b25.zip/arlo_plugin/arlo/request.py", line 67, in _request
    r.raise_for_status()
  File "/Users/michele/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Darwin-x86_64/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ocapi-app.arlo.com/api/auth?eventId=FE!8e0e0411-01ff-4ac1-84d7-c399edf214b7&time=1684175112529`

**Comment by fierrogt** [comment]
Same as [bubez81]. 0.7.15 still not working: 

> darwin x64 Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64
server version: 0.7.97
plugin version: @scrypted/arlo 0.7.15
########################
5/16/2023, 12:16:22 PM
########################
python version: python3.9
python prefix: /Users/brandon/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Darwin-x86_64
requirements.txt (up to date)
paho-mqtt==1.6.1
sseclient==0.0.22
requests==2.28.2
cachetools==5.3.0
scrypted-arlo-go==0.0.1
cloudscraper==1.2.71
--extra-index-url=https://www.piwheels.org/simple/
--extra-index-url=https://bjia56.github.io/scrypted-arlo-go/
--prefer-binary
site-packages: /Users/brandon/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Darwin-x86_64/lib/python3.9/site-packages
Setting plugin verbosity to Verbose
Setting plugin transport to SSE
[Arlo provider] Trying to initialize Arlo client...
Traceback (most recent call last):
  File "/Users/brandon/.scrypted/volume/plugins/@scrypted/arlo/zip/1-01c36b3759f1bb6878ff4cd646eb6b25.zip/arlo_plugin/provider.py", line 182, in arlo
    self._arlo_mfa_complete_auth = self._arlo.LoginMFA()
  File "/Users/brandon/.scrypted/volume/plugins/@scrypted/arlo/zip/1-01c36b3759f1bb6878ff4cd646eb6b25.zip/arlo_plugin/arlo/arlo_async.py", line 154, in LoginMFA
    auth_body = self.request.post(
  File "/Users/brandon/.scrypted/volume/plugins/@scrypted/arlo/zip/1-01c36b3759f1bb6878ff4cd646eb6b25.zip/arlo_plugin/arlo/request.py", line 91, in post
    return self._request(url, 'POST', **kwargs)
  File "/Users/brandon/.scrypted/volume/plugins/@scrypted/arlo/zip/1-01c36b3759f1bb6878ff4cd646eb6b25.zip/arlo_plugin/arlo/request.py", line 67, in _request
    r.raise_for_status()
  File "/Users/brandon/.scrypted/volume/plugins/@scrypted/arlo/python3.9-Darwin-x86_64/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ocapi-app.arlo.com/api/auth?eventId=FE!f11db5a5-f42d-448f-a14e-e81c3f70a59e&time=1684253782454
[Arlo provider] Cannot create device for nativeId A8C10AK8A3744, maybe it hasn't been loaded yet?

**Comment by bjia56** [comment]
Let's continue the conversation in #795 since this issue is already closed
